apiVersion: v1
kind: Pod
metadata:
  name: httpbin
  namespace: dev
  labels:
    app: httpbin
spec:
  containers:
    - name: httpbin
      image: postman/httpbin
      ports:
        - containerPort: 80
